name: Deploy to VM

on:
  push:
    branches:
      - main  # Change this to the branch you want to deploy from (e.g., 'main' or 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for running the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This checks out the code from GitHub repository

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3  # This will add the private SSH key for authentication
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # This is the secret you stored in GitHub

    - name: Deploy to VM
      run: |
        ssh -v -o StrictHostKeyChecking=no LENOVO@34.18.97.231 << 'EOF'
          # Check if PM2 is installed
          if ! command -v pm2 &> /dev/null; then
            echo "PM2 not found. Installing PM2..."
            npm install -g pm2  # Install PM2 globally
          else
            echo "PM2 is already installed."
          fi

          # Deploy the application
          cd /home/LENOVO/googlesheet-dashboard && \
          git pull origin main && \
          npm install --legacy-peer-deps && \
          npm run build && \
          pm2 restart nextjs-app
        EOF
